image:
  repository: menta2l/k8-injector
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

replicaCount: 1

service:
  port: 443

container:
  port: 8443

podAnnotations: {}
podLabels: {}
podSecurityContext: {}

sidecars:
  dataKey: sidecars.yaml

selectors:
  injectPrefix: injector.server-lab.info
  injectName: inject
  disableInjectLabel: disable-inject
  objectSelector: {}
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
          - kube-public
