apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        injector.server-lab.info/inject: "haystack-agent-sidecar"
        injector.server-lab.info/config: "test-config"
        injector.server-lab.info/some-api-key: "6feab492-fc9b-4c38-b50d-3791718c820322"
        injector.server-lab.info/some-api-key-xxx: "6feab492-fc9b-4c38-b50d-3791718c820322"
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: echo-server
          image: hashicorp/http-echo:alpine
          imagePullPolicy: IfNotPresent
          env:
          - name: APP_ENV
            value: "dev"
          args:
            - -listen=:8080
            - -text="hello world"
