apiVersion: {{ include "common.capabilities.rbac.apiVersion" .}}
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.names.name" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "common.names.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "common.names.name" . }}
    namespace: {{ .Release.Namespace | quote }}