{{- if .Values.webhook.createCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.name" . }}-certs
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
data:
{{ ( include "webhook.gen-certs" . ) | indent 2 }}
{{- end }}